<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laboratory 64</title>
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
<div class="container">
<form id="task-form" name="form" enctype="multipart/form-data">
    <input type="text" id="value" placeholder="task" name="task" autofocus />
    <button  type="button" id="save-task">Добавить</button>
    <div id="task" class="createTask">

    </div>
</form>
    </div>
 </body>
</html>

<script src="/js/task.js"></script>
